---
title: "Review_Work"
output: html_document
date: "2025-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,cache=TRUE)
```


```{r}
#LOAD RELEVANT LIBRARIES
library(ggplot2)
library(dplyr)
library(grid)
library(ggpubr)
require(grid)

data = read.table('../data/figure_1C_data.tsv', header=TRUE) #load the data

#Generate average number of IAV virus and non-IAV virus reads for each dilution and protocol
#Using standard devition for based on total number of reads
summarised_data = data %>%
  group_by(condition, dilution) %>%
    summarise(mean_total_reads = mean(total_reads),N=n(),
              mean_assembled_reads = mean(total_assembled),
              mean_non_virus_reads = mean(non_virus_reads),
              sd_total_reads = sd(total_reads),
              SE_tota_reads = sd_total_reads/sqrt(N)) %>%
    mutate(ymax_total_reads = mean_total_reads + SE_tota_reads,
          ymin_total_reads = mean_total_reads - SE_tota_reads)


#Just a function to restructure the data for ease of plotting
process_plot <- function(protocol){
      df = summarised_data %>% filter(condition == protocol)
      df = df %>% select(dilution,mean_assembled_reads, mean_non_virus_reads,
                         ymax_total_reads,ymin_total_reads) %>%
    tidyr::pivot_longer(cols=c(mean_assembled_reads, mean_non_virus_reads), names_to=c('variabl2e'))
    return(df)
}

#GGplot function to generate the figure
plot_image <- function(data, title){

  order=c('mean_non_virus_reads','mean_assembled_reads')
  fig <- ggplot(data,aes(x=dilution, y=value,fill=factor(variabl2e, levels=order) ))  +
          geom_bar(stat='identity', width = 0.55, position ='stack')+ 
          labs(fill='',y = 'Average No. of Reads \n (x1000)',x='Dilution', title = title) +
          scale_y_continuous(limits = c(0, 250000),labels=c("0","50","100","150","200","250")) + 
          geom_errorbar(aes(ymax = ymax_total_reads, ymin=ymin_total_reads),width = 0.4)+
          theme_classic()+
          scale_fill_manual(values = c("mean_non_virus_reads"="#b2182b", "mean_assembled_reads"="#bababa"),
                    labels = c("mean_non_virus_reads" = "Non-Viral","mean_assembled_reads" = "Viral"))+
          theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
              plot.title = element_text(hjust = 0.5, size=8, color = 'black', face='bold'),
              axis.text = element_text(size=9, color='black')) +
          guides(color = guide_legend(override.aes = list(size=5)))
  return(fig)
}


#run the functions
L5 = plot_image(process_plot('Licheri_5uM'),'Current Study')
R3 = plot_image(process_plot( 'Rambo_3P'),'Rambo-Martin et al.')
Z3 = plot_image(process_plot('Zhou_3P'),'Zhou et al. 2012')
Z2 = plot_image(process_plot('Zhou_2P'),'Zhou et al. 2009')


#merge the individual images and save
figure = ggarrange(Z2,Z3,R3,L5,nrow=1, common.legend = T,legend='top')
final_plot <- annotate_figure(figure, 
                  left = text_grob('Average No. of Reads \n (x1000)',rot=90, size = 11),
              bottom = text_grob("Dilution", size = 11))

ggsave('../Figures/Figure_1C.pdf',plot= final_plot, width=10, height=3)


```
