---
title: "Review_Work"
output: html_document
date: "2025-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message=FALSE)
```


```{r,warning=FALSE, message=FALSE}
pacman::p_load(ggplot2,grid, ggpubr,reshape,data.table)
```


```{r}
path='../data/'
data = read.table(paste0(path, 'Figure_99_subsampled_AB.tsv'), header=T, na.strings = "NA")

#Generate average number of IAV virus and non-IAV virus reads for each dilution and protocol
#Using standard deviation for based on total number of reads
summarised_data = data %>%
  group_by(condition, dilution) %>%
    summarise(mean_total_reads = mean(total_reads),N=n(),
              mean_assembled_reads = mean(total_assembled),
              mean_non_virus_reads = mean(non_virus_reads),
              mean_HA = mean(HA),mean_NA = mean(NA.),mean_NS = mean(NS),
              mean_NP = mean(NP),mean_MP = mean(MP),mean_PA = mean(PA),
              mean_PB1 = mean(PB1),mean_PB2= mean(PB2))


colorcode=c('Non_Virus'="black","PA"='#a1d99b','PB1'='#e0bb2b', 'PB2'='#238b45', 'HA'='#e31a1c','NP'='#9e9ac8',
            'MP'='#1d91c0','NS'='#41b6c4','NA'="#fd8d3c")

order=c('Non_Virus','PB2','PB1','PA','HA','NP','NA','NS','MP')

stack_plot_data = summarised_data %>% 
            select(condition, dilution,mean_non_virus_reads,mean_PB2,mean_PB1,mean_PA,mean_HA,mean_NP,mean_NA,mean_NS,mean_MP) %>%  
            setnames(old=c('mean_PA','mean_PB1','mean_PB2','mean_HA','mean_NA','mean_MP','mean_NP','mean_NS','mean_non_virus_reads'),
                     new=c('PA','PB1','PB2','HA','NA','MP','NP','NS','Non_Virus')) %>%
            tidyr::pivot_longer(cols= c(PB2,PB1,PA,HA,NP,'NA',NS,MP,Non_Virus),names_to = 'variable')

stack_plot_data$variable <- factor(replace(as.character(stack_plot_data$variable), 
                                           is.na(stack_plot_data$variable), "NA"),levels = order)

generate_plot_gene <- function(protocol){
    data_condition <- stack_plot_data %>% dplyr::filter(condition == protocol)
    figure <- ggplot(data_condition, aes(fill=factor(variable,levels=order), y=value, x=dilution)) + 
                geom_bar(position="stack", stat="identity",width = 0.80) +
                labs(fill='',x='Dilution', title ='') +
                scale_fill_manual(values=colorcode)+ 
                scale_y_continuous(limits = c(0, 12000),labels=c("0","25","50","75","100","125"))+
                theme_classic() +
                theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
                      plot.title = element_text(hjust = 0.5, size=8, color = 'black', face='bold'),
                      axis.text = element_text(size=9, color='black'),
                      legend.key.size = unit(0.3,"cm"),legend.text = element_text(size = 8)) +
                guides(fill=guide_legend(nrow=1),color = guide_legend(override.aes = list(size=5)))
    return(figure)
    
}

Z3 <- generate_plot_gene('Zhou_3P')
Z2 <- generate_plot_gene('Zhou_2P')
R3 <- generate_plot_gene('Rambo_3P')
L5 <- generate_plot_gene('Licheri_5uM')

figure = ggarrange(Z2,Z3,R3,L5,nrow=1, common.legend = T,legend='top',font.label=list(size=10,face='bold'),
                   labels=c('Zhou et al. 09','Zhou et al. 12','Rambo et al','Current Study'))
final_plot <- annotate_figure(figure,
                  left = text_grob('No. of Sampled Reads \n (x100)',rot=90, size = 12),
              bottom = text_grob("Dilution", size = 13))
ggsave(paste0(path,'../Figures/Figure_99_subsampled_B.pdf'),plot= final_plot, width=8, height=3)


```



